my_file = open('file_2.txt', 'r')
content = my_file.read()
print(f'File content: \n {content}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
print(f'Number of lines in folder - {len(content)}')
my_file = open('file_2.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Number of symbols {i + 1} - in line number {len(content[i])}')
my_file = open('file_2.txt', 'r')
content = my_file.read()
content = content.split()
print(f'General number of words - {len(content)}')
my_file.close()